/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Brayan Machado
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        btn_GuardarContacto = new javax.swing.JButton();
        btn_VisualizarContactos = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_Visualizar = new javax.swing.JTextArea();
        btn_HuecosLibres = new javax.swing.JButton();
        btn_VerificarAgenda = new javax.swing.JButton();
        btn_BuscarContacto = new javax.swing.JButton();
        btn_ExisteContacto = new javax.swing.JButton();
        btn_EliminarContacto = new javax.swing.JButton();
        btn_GuardarArchivo = new javax.swing.JButton();
        btn_LeerArchivo = new javax.swing.JButton();
        btn_EliminarReArchivo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("CONTACTOS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 33, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("NOMBRE :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 118, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("TELEFONO :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 178, -1, -1));

        txt_Nombre.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jPanel1.add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 150, -1));

        txt_telefono.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 150, -1));

        btn_GuardarContacto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_GuardarContacto.setText("GUARDAR CONTACTO");
        btn_GuardarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarContactoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_GuardarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 199, 54));

        btn_VisualizarContactos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_VisualizarContactos.setText("LISTAR CONTACTOS");
        jPanel1.add(btn_VisualizarContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 199, 61));

        txt_Visualizar.setColumns(20);
        txt_Visualizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Visualizar.setRows(5);
        jScrollPane3.setViewportView(txt_Visualizar);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 269, 430, 250));

        btn_HuecosLibres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_HuecosLibres.setText("HUECOS LIBRES");
        jPanel1.add(btn_HuecosLibres, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 178, 54));

        btn_VerificarAgenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_VerificarAgenda.setText("VERIFICAR AGENDA");
        jPanel1.add(btn_VerificarAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 178, 60));

        btn_BuscarContacto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_BuscarContacto.setText("BUSCAR CONTACTO");
        jPanel1.add(btn_BuscarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 180, 56));

        btn_ExisteContacto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ExisteContacto.setText("COMPROBAR SI EXITE CONTACTO");
        jPanel1.add(btn_ExisteContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, 54));

        btn_EliminarContacto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_EliminarContacto.setText("ELIMINAR CONTACTO");
        jPanel1.add(btn_EliminarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 200, 60));

        btn_GuardarArchivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_GuardarArchivo.setText("GUARDAR ARCHIVO");
        jPanel1.add(btn_GuardarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 200, 50));

        btn_LeerArchivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LeerArchivo.setText("LEER ARCHIVO");
        jPanel1.add(btn_LeerArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 180, 50));

        btn_EliminarReArchivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_EliminarReArchivo.setText("ELIMINAR REGISTRO ARCHIVO");
        jPanel1.add(btn_EliminarReArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 250, 50));

        jTabbedPane1.addTab("GUARDAR CONTACTO", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GuardarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_GuardarContactoActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_BuscarContacto;
    public javax.swing.JButton btn_EliminarContacto;
    public javax.swing.JButton btn_EliminarReArchivo;
    public javax.swing.JButton btn_ExisteContacto;
    public javax.swing.JButton btn_GuardarArchivo;
    public javax.swing.JButton btn_GuardarContacto;
    public javax.swing.JButton btn_HuecosLibres;
    public javax.swing.JButton btn_LeerArchivo;
    public javax.swing.JButton btn_VerificarAgenda;
    public javax.swing.JButton btn_VisualizarContactos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField txt_Nombre;
    public javax.swing.JTextArea txt_Visualizar;
    public javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
